import type { Metadata } from "next";
import { Geist, Geist_Mono, Funnel_Sans, Funnel_Display } from "next/font/google";
import "./globals.scss";
import styles from './page.module.scss'
import localFont from "next/font/local";
import { ViewTransitions } from "next-view-transitions";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const funnelSans = Funnel_Sans({
  variable: "--font-funnel-sans",
  subsets: ["latin"],
});

const funnelDisplay = Funnel_Display({
  variable: "--font-funnel-display",
  subsets: ["latin"],
});


const cozetteFont = localFont({
  src: './CozetteVector.ttf',
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <ViewTransitions>
      <html lang="en">
        <head>
          <script type="x-shader/x-vertex" id="vertexshader">
            {
              `
              varying vec2 vUv;

              void main() {
                vUv = uv;
                gl_Position = projectionMatrix * modelViewMatrix * vec4(position, 1.0);
              }
              `
            }
          </script>
          <script type="x-shader/x-fragment" id="fragmentshader">
            {
              `
              uniform sampler2D baseTexture;
              uniform sampler2D bloomTexture;

              varying vec2 vUv;

              void main() {

                gl_FragColor = ( texture2D( baseTexture, vUv ) + vec4( 1.0 ) * texture2D( bloomTexture, vUv ) );

              }
              `
            }
          </script>
        </head>
        <body className={[geistSans.variable, geistMono.variable, funnelSans.variable, funnelDisplay.variable].join(' ')}>
          <main className={[styles.layout, cozetteFont.className].join(' ')}>
            {children}
          </main>
        </body>
      </html>
    </ViewTransitions>
  );
}
